`Raspberry Pi Image Builder`
ver. 4.4
mainline: support removed (use other builder)
make config: now supports admin option
make menu: interface redone and cards now pulled as board.txt
builder: rewrite

diff --git a/lib/dialog/menu b/lib/dialog/menu
--- a/lib/dialog/menu
+++ b/lib/dialog/menu
@@ -4,59 +4,61 @@ RED="\e[0;31m"
 FIN="\e[0m"
 DIALOG_CANCEL=1
 DIALOG_ESC=255
+HEIGHT=0
+WIDTH=0
 
+source lib/source > /dev/null 2>&1
+UD=userdata.txt > /dev/null 2>&1
+userdata(){
+echo ""
+echo "Please create a userdata.txt file"
+while [ true ]; do
+read -t 10 -n 1
+if [ $? = 0 ]; then
+	exit;
+else
+	echo "run make config";
+fi
+done
+}
+
+if [ -f "$UD" ]; then
+	echo "";
+else 
+	userdata;
+fi
+validation
+menu_items=`ls lib/boards | while read name; do ((count+=1)); echo $count $name | sed -e 's/\(.*\)/\U\1/'; done`
 while true; do
-  exec 3>&1
-  selection=$(dialog --colors \
-    --backtitle "Raspberry Pi Image Builder" \
-    --title "Boards" \
-    --clear \
-    --cancel-label "Exit" \
-    --menu "Select:" 0 40 0 \
-    "1" "Raspberry Pi 4 (ARM64)" \
-    "2" "Raspberry Pi 4 (ARMHF)" \
-    "3" "Raspberry Pi 3/A/B/+" \
-    "4" "Raspberry Pi 2/3/A/B/+" \
-    "5" "Raspberry Pi 0/W/B/+" \
-    2>&1 1>&3)
-  exit_status=$?
-  exec 3>&-;
-  case $exit_status in
-    $DIALOG_CANCEL)
-      clear
-      echo -e "${RED}Program terminated${FIN}."
-      exit
-      ;;
-    $DIALOG_ESC)
-      clear
-      echo -e "${RED}Program aborted${FIN}." >&2
-      exit 1
-      ;;
-  esac
-  case $selection in
-    0 )
-      clear
-      echo -e "%{RED}Program terminated${FIN}."
-      ;;
-    1 )
-      chmod +x lib/dialog/rpi4
-      ./lib/dialog/rpi4
-      ;;
-    2 )
-      chmod +x lib/dialog/rpi4v7
-      ./lib/dialog/rpi4v7
-      ;;
-    3 )
-      chmod +x lib/dialog/rpi3
-      ./lib/dialog/rpi3
-      ;;
-    4 )
-      chmod +x lib/dialog/rpi2+3
-      ./lib/dialog/rpi2+3
-      ;;
-    5 )
-      chmod +x lib/dialog/rpi
-      ./lib/dialog/rpi
-      ;;
-  esac
+	exec 3>&1
+	selection=$(dialog \
+	--backtitle "Raspberry Pi Image Builder" \
+	--title "Boards" \
+	--clear \
+	--cancel-label "Exit" \
+	--menu "Select:" $HEIGHT $WIDTH 3 \
+	$menu_items \
+ 	2>&1 1>&3)
+ 	exit_status=$?
+ 	exec 3>&-;
+case $exit_status in
+	$DIALOG_CANCEL)
+		clear -x
+		echo -e "${RED}Program terminated${FIN}."
+		exit
+		;;
+	$DIALOG_ESC)
+		clear -x
+		echo -e "${RED}Program aborted${FIN}." >&2
+		exit 1
+		;;
+esac
+if [ $selection .eq 0 ]; then
+	clear -x;
+	echo -e "${RED}Program terminated${FIN}.";
+else
+	boardName=`ls lib/boards | head -n $selection | tail -n 1`; 
+	chmod +x lib/dialog/general;
+	./lib/dialog/general $boardName;
+fi
 done
