If qemu is not installed stop script and alert user
Signed-off-by: Patrick Yavitz <pyavitz@xxxxx.com>

diff --git a/scripts/rootfs b/scripts/rootfs
--- a/scripts/rootfs
+++ b/scripts/rootfs
@@ -53,6 +53,14 @@ else
 		ubuntu_setup
 	fi
 fi
+# check for qemu
+if [[ `command -v ${STATIC}` ]]; then
+	:;
+else
+	echo -e "Missing depends: ${STATIC}"
+	echo -e "Run ./install.sh"
+	exit 1
+fi
 
 ROOT="sysroot"
 RELEASE_TARBALL=${DISTRO}-${DISTRO_VERSION}-${ROOTFS_ARCH}.tar.xz
diff --git a/scripts/stage1 b/scripts/stage1
--- a/scripts/stage1
+++ b/scripts/stage1
@@ -48,6 +48,14 @@ else
 fi
 # verbose
 if [ $VERBOSE -eq 1 ]; then set -eux -o pipefail; else set -eu -o pipefail; fi
+# check for qemu
+if [[ `command -v ${STATIC}` ]]; then
+	:;
+else
+	echo -e "Missing depends: ${STATIC}"
+	echo -e "Run ./install.sh"
+	exit 1
+fi
 
 CAP_DISTRO=`echo "${DISTRO}" | sed -e "s/\b\(.\)/\u\1/g"`
 CAP_RELEASE=`echo "${DISTRO_VERSION}" | sed -e "s/\b\(.\)/\u\1/g"`
