Devuan: `maintenance`

diff --git a/files/devuan/patches/raspberrypi-sys-mods-postinst.patch b/files/devuan/patches/raspberrypi-sys-mods-postinst.patch
--- a/files/devuan/patches/raspberrypi-sys-mods-postinst.patch
+++ b/files/devuan/patches/raspberrypi-sys-mods-postinst.patch
@@ -1,6 +1,17 @@
 --- a/debian/raspberrypi-sys-mods.postinst	2021-11-22 09:02:59.417245204 -0500
-+++ b/debian/raspberrypi-sys-mods.postinst	2021-11-22 09:29:46.602344954 -0500
-@@ -66,10 +66,6 @@
++++ b/debian/raspberrypi-sys-mods.postinst	2021-11-22 09:44:16.200076826 -0500
+@@ -41,10 +41,6 @@
+     if dpkg --compare-versions "${2}" lt "20160112"; then
+       check_audio
+     fi
+-    if dpkg --compare-versions "${2}" lt "20160321+1"; then
+-      echo "Fixing file capabilities..."
+-      setcap cap_dac_override,cap_sys_ptrace+ep /usr/bin/systemd-detect-virt || true
+-    fi
+     if dpkg --compare-versions "${2}" lt "20160321"; then
+       echo "Adjusting cmdline.txt..."
+       sed -e "s|=ttyAMA0|=serial0|;s|=ttyS0|=serial1|;" -i /boot/cmdline.txt || echo "Failed"
+@@ -66,10 +62,6 @@
        echo "Updating documentation URL in /boot/config.txt..."
        sed -i 's|http://www.raspberrypi.org/documentation/configuration/config-txt.md|http://rpf.io/configtxtreadme|' /boot/config.txt || echo "Failed"
      fi
